-- FarmLasso.SoundKit: every sound in the game plays through here (Oct 7 2026).
--
--   local Snd = require(ReplicatedStorage.FarmLasso.SoundKit)
--   Snd.Play("CatchChime")                                  -- 2D, the cue's own volume and pitch spread
--   Snd.Play("RopeLand", {At = animalPart, Volume = .8})    -- 3D from a part / attachment / Vector3
--   local h = Snd.Loop("LassoCharge")  h:Set(charge)  h:Stop(.2)   -- a loop with an intensity curve
--   Snd.Duck("Music", .3, 5)                                -- dip a group for 5 s, ease back
--   Snd.SetVolume("Music", .5)  Snd.GetVolume("Music")      -- the player's sliders (0..1)
--
-- Cues live in SoundCues (name -> file stem, volume, pitch spread, group, rolloff, cooldown, loop curves); the file
-- stems map to asset ids in SoundIds (generated by audio/build_sfx_pack.py --lua). A cue whose files have no id yet
-- plays nothing and warns once, so the game runs with a half-uploaded pack.
--
-- Groups (SoundGroups under SoundService, made client-side on first use):
--   Master > Music, SFX (> UI, Celebration), Ambience.  Volume = default x the player's slider x the duck.
-- Budget: at most 24 one-shots (14 on touch) and 8 loops at once; the oldest one-shot is dropped first. A cue can't
-- start twice inside its cooldown (default 40 ms). Variants round-robin and never repeat back to back.
-- Server: everything is a no-op (sounds are client-side), so modules shared with the server can require this safely.
local SoundService = game:GetService("SoundService")
local RunService = game:GetService("RunService")
local UserInputService = game:GetService("UserInputService")
local ContentProvider = game:GetService("ContentProvider")

local okCues, Cues = pcall(require, script.Parent:FindFirstChild("SoundCues") or script)
if not okCues or type(Cues) ~= "table" then Cues = {} end
local okIds, Ids = pcall(require, script.Parent:FindFirstChild("SoundIds") or script)
if not okIds or type(Ids) ~= "table" then Ids = {} end

local K = {}
K.IsClient = RunService:IsClient()
K.Mobile = UserInputService.TouchEnabled and not UserInputService.KeyboardEnabled
K.Defaults = {Master = 1, Music = .45, SFX = 1, UI = .8, Celebration = 1, Ambience = .35}
K.Sliders = {"Music", "SFX", "Ambience"} -- what the settings panel shows (UI and Celebration follow SFX)
K.MaxOneShots = K.Mobile and 14 or 24
K.MaxLoops = 8
K.Cues = Cues
K.Ids = Ids

local TREE = {Music = "Master", SFX = "Master", Ambience = "Master", UI = "SFX", Celebration = "SFX"}
local groups, state = {}, {}   -- name -> SoundGroup; name -> {User = 1, Duck = 1, DuckTarget = 1, DuckUntil = 0}
local pool = {}                -- file stem -> {Sound, ...}
local playing = {}             -- one-shot handles, oldest first
local loops = {}               -- loop handles
local lastAt, lastVariant = {}, {}
local warned = {}
local anchors = {}             -- free attachments for Vector3 positions
local listeners = {}           -- volume-changed callbacks

---------------------------------------------------------------- groups and volumes
local function applyVolume(name)
	local g, s = groups[name], state[name]
	if g and s then g.Volume = (K.Defaults[name] or 1) * s.User * s.Duck end
end
local function group(name)
	if not K.IsClient then return nil end
	if groups[name] then return groups[name] end
	local parentName = TREE[name]
	local parent = parentName and group(parentName) or SoundService
	local g = parent:FindFirstChild("FL_" .. name)
	if not g then
		g = Instance.new("SoundGroup")
		g.Name = "FL_" .. name
		g.Parent = parent
	end
	groups[name] = g
	state[name] = state[name] or {User = 1, Duck = 1, DuckTarget = 1, DuckUntil = 0, DuckFade = .6}
	applyVolume(name)
	return g
end
-- the player's slider for a group (0..1). UI and Celebration follow SFX unless set on their own.
function K.SetVolume(name, v)
	v = math.clamp(tonumber(v) or 1, 0, 1)
	group(name)
	if not state[name] then return end
	state[name].User = v
	applyVolume(name)
	if name == "SFX" then
		for _, child in {"UI", "Celebration"} do
			group(child)
			state[child].User = v
			applyVolume(child)
		end
	end
	for _, fn in listeners do task.spawn(fn, name, v) end
end
function K.GetVolume(name)
	group(name)
	return state[name] and state[name].User or 1
end
function K.Volumes()
	local out = {}
	for _, n in K.Sliders do out[n] = K.GetVolume(n) end
	return out
end
function K.LoadVolumes(tbl)
	if type(tbl) ~= "table" then return end
	for _, n in K.Sliders do if tbl[n] ~= nil then K.SetVolume(n, tbl[n]) end end
end
function K.OnVolumeChanged(fn) table.insert(listeners, fn) end
-- dip a group to `level` (0..1 of its normal volume) for `hold` seconds, then ease back over `fade` (default .6).
-- Overlapping ducks keep the lowest level and the latest end time.
function K.Duck(name, level, hold, fade)
	group(name)
	local s = state[name]
	if not s then return end
	local now = os.clock()
	local untilT = now + (hold or 1)
	if s.DuckUntil > now then
		s.DuckTarget = math.min(s.DuckTarget, level)
		s.DuckUntil = math.max(s.DuckUntil, untilT)
	else
		s.DuckTarget = level
		s.DuckUntil = untilT
	end
	s.DuckFade = fade or .6
end
-- hold a duck until the returned function is called (celebrations of unknown length, menus)
function K.DuckHold(name, level)
	K.Duck(name, level, 3600, .6)
	return function()
		local s = state[name]
		if s then s.DuckUntil = os.clock() end
	end
end

---------------------------------------------------------------- cue lookup
local function snake(name: string)
	local out = {}
	for i = 1, #name do
		local c = name:sub(i, i)
		local prev, nxt = name:sub(i - 1, i - 1), name:sub(i + 1, i + 1)
		if i > 1 and c:match("%u") and (not prev:match("%u") or nxt:match("%l")) then table.insert(out, "_") end
		table.insert(out, c:lower())
	end
	return table.concat(out)
end
local fileCache = {}
-- the pack files a cue can pick from: <stem> or <stem>_1, _2 ... (only those with an id pasted in)
local function filesFor(name, def)
	if fileCache[name] then return fileCache[name] end
	local stem = def.File or snake(name)
	local files, missing = {}, 0
	local function try(key)
		local id = Ids[key]
		if id == nil then return false end
		if type(id) == "string" and id ~= "" and id ~= "0" then table.insert(files, {Key = key, Id = id}) else missing += 1 end
		return true
	end
	if not try(stem) then
		local i = 1
		while try(stem .. "_" .. i) do i += 1 end
	end
	if #files == 0 and not warned[name] then
		warned[name] = true
		if missing > 0 then
			warn("[SoundKit] " .. name .. ": no asset id pasted into SoundIds for '" .. stem .. "' yet (silent)")
		else
			warn("[SoundKit] " .. name .. ": no pack file '" .. stem .. "' in SoundIds (silent)")
		end
	end
	fileCache[name] = files
	return files
end
local function cue(name)
	local def = Cues[name]
	if not def then
		if not warned[name] then warned[name] = true warn("[SoundKit] unknown cue " .. tostring(name)) end
		return nil
	end
	return def
end
local function pickFile(name, files)
	if #files == 1 then return files[1] end
	local last = lastVariant[name]
	local i = math.random(1, #files - 1)
	if last and i >= last then i += 1 end
	lastVariant[name] = i
	return files[i] or files[1]
end
local function spread(range, rng)
	if type(range) == "number" then return range end
	if type(range) == "table" then return range[1] + (range[2] - range[1]) * (rng or math.random()) end
	return 1
end

---------------------------------------------------------------- instances
local function acquire(file, def)
	local list = pool[file.Key]
	if not list then list = {} pool[file.Key] = list end
	for _, s in list do
		if not s.IsPlaying and not s:GetAttribute("Busy") then return s end
	end
	local s = Instance.new("Sound")
	s.Name = "FL_" .. file.Key
	s.SoundId = file.Id
	s.RollOffMode = Enum.RollOffMode.InverseTapered
	table.insert(list, s)
	return s
end
local function anchor(pos)
	local a = table.remove(anchors)
	if not a then
		a = Instance.new("Attachment")
		a.Name = "FL_SoundAnchor"
		a.Parent = workspace.Terrain
	end
	a.WorldPosition = pos
	return a
end
local function placeSound(s, at, def)
	local release
	if typeof(at) == "Vector3" then
		local a = anchor(at)
		s.Parent = a
		release = function() if a.Parent then table.insert(anchors, a) end end
	elseif typeof(at) == "Instance" and (at:IsA("BasePart") or at:IsA("Attachment")) then
		s.Parent = at
	elseif typeof(at) == "Instance" and at:IsA("Model") then
		s.Parent = at.PrimaryPart or at:FindFirstChildWhichIsA("BasePart") or SoundService
	else
		s.Parent = SoundService
	end
	if s.Parent ~= SoundService then
		s.RollOffMinDistance = def.Min or 8
		s.RollOffMaxDistance = def.Max or 80
	end
	return release
end

-- a handle wraps one Sound for the caller: Stop(fade), SetVolume, SetPitch, SetRate, Set(intensity) for loops
local Handle = {}
Handle.__index = Handle
function Handle:Apply()
	local s = self.Sound
	if not s then return end
	s.PlaybackSpeed = math.clamp(self.Pitch * self.Rate, .05, 8)
	s.Volume = math.clamp(self.Volume * self.Scale, 0, 10)
end
function Handle:SetVolume(v) self.Volume = v or self.Volume self:Apply() end
function Handle:SetPitch(p) self.Pitch = p or self.Pitch self:Apply() end
function Handle:SetRate(r) self.Rate = r or 1 self:Apply() end
-- loops: 0..1 along the cue's Curve (Pitch / Volume ranges); smoothed so a jittery input doesn't buzz
function Handle:Set(k)
	self.Target = math.clamp(tonumber(k) or 0, 0, 1)
end
function Handle:Stop(fade)
	if self.Done then return end
	self.Done = true
	local s = self.Sound
	fade = fade or 0
	local function finish()
		if s then s:Stop() s:SetAttribute("Busy", nil) end
		if self.Release then self.Release() end
		if s and s.Parent ~= SoundService and s.Parent then s.Parent = SoundService end
	end
	if fade > 0 and s and s.IsPlaying then
		local v0 = s.Volume
		local t0 = os.clock()
		self.Fading = function()
			local u = (os.clock() - t0) / fade
			if u >= 1 then finish() return true end
			s.Volume = v0 * (1 - u)
		end
	else
		finish()
	end
end

local stepConn
local function ensureStep()
	if stepConn or not K.IsClient then return end
	stepConn = RunService.Heartbeat:Connect(function(dt)
		local now = os.clock()
		-- ducks ease toward their target and back after their hold
		for name, s in state do
			local target = s.DuckUntil > now and s.DuckTarget or 1
			local rate = (target < s.Duck and .15 or s.DuckFade or .6)
			local step = dt / math.max(.05, rate)
			local nd = s.Duck + math.clamp(target - s.Duck, -step, step)
			if math.abs(nd - s.Duck) > 1e-4 then s.Duck = nd applyVolume(name) end
		end
		-- loops follow their intensity, with smoothing
		for i = #loops, 1, -1 do
			local h = loops[i]
			if h.Done then
				if not h.Fading or h.Fading() then table.remove(loops, i) end
			else
				local k = h.Target or 0
				h.K += (k - h.K) * math.min(1, dt * 12)
				local c = h.Curve or {}
				local p, v = c.Pitch, c.Volume
				h.Pitch = p and (p[1] + (p[2] - p[1]) * h.K) or h.BasePitch
				h.Volume = h.BaseVolume * (v and (v[1] + (v[2] - v[1]) * h.K) or 1)
				h:Apply()
			end
		end
		for i = #playing, 1, -1 do
			local h = playing[i]
			if h.Done then
				if not h.Fading or h.Fading() then table.remove(playing, i) end
			elseif not h.Sound.IsPlaying and now - h.T0 > .1 then
				h:Stop()
				table.remove(playing, i)
			end
		end
	end)
end

---------------------------------------------------------------- play
-- Play a cue. o: At (part / attachment / Vector3 / Model; nil = 2D), Volume (x cue), Pitch (x cue spread), Rate,
-- Group (override), Delay (s), Cooldown (override). Returns a handle or nil (silent / budget / cooldown).
function K.Play(name, o)
	if not K.IsClient then return nil end
	local def = cue(name)
	if not def then return nil end
	o = o or {}
	if o.Delay and o.Delay > 0 then
		local d = table.clone(o) d.Delay = nil
		task.delay(o.Delay, K.Play, name, d)
		return nil
	end
	local now = os.clock()
	local cd = o.Cooldown or def.Cooldown or .04
	if lastAt[name] and now - lastAt[name] < cd then return nil end
	local files = filesFor(name, def)
	if #files == 0 then return nil end
	lastAt[name] = now
	ensureStep()
	if def.Loop then return K.Loop(name, o) end
	if #playing >= K.MaxOneShots then
		local victim = table.remove(playing, 1)
		if victim then victim:Stop() end
	end
	local file = pickFile(name, files)
	local s = acquire(file, def)
	s:SetAttribute("Busy", true)
	s.Looped = false
	s.SoundGroup = group(o.Group or def.Group or "SFX")
	local h = setmetatable({Sound = s, Name = name, T0 = now, Rate = o.Rate or 1, Scale = 1,
		Pitch = spread(o.Pitch or 1) * spread(def.Pitch or {.95, 1.05}), Volume = (def.Volume or .7) * (o.Volume or 1)}, Handle)
	h.Release = placeSound(s, o.At, def)
	h:Apply()
	s.TimePosition = 0
	s:Play()
	table.insert(playing, h)
	return h
end
-- Start a looping cue; the handle's :Set(k) runs the cue's Curve, :Stop(fade) ends it. Fades in over def.FadeIn (.25).
function K.Loop(name, o)
	if not K.IsClient then return nil end
	local def = cue(name)
	if not def then return nil end
	o = o or {}
	local files = filesFor(name, def)
	if #files == 0 then return nil end
	ensureStep()
	if #loops >= K.MaxLoops then
		local victim = table.remove(loops, 1)
		if victim then victim:Stop(.1) end
	end
	local file = pickFile(name, files)
	local s = acquire(file, def)
	s:SetAttribute("Busy", true)
	s.Looped = true
	s.SoundGroup = group(o.Group or def.Group or "SFX")
	local h = setmetatable({Sound = s, Name = name, T0 = os.clock(), Rate = o.Rate or 1, Scale = 0, Loop = true, K = 0, Target = o.K or 0,
		BasePitch = spread(o.Pitch or 1) * spread(def.Pitch or 1), BaseVolume = (def.Volume or .5) * (o.Volume or 1), Curve = def.Curve}, Handle)
	h.Pitch, h.Volume = h.BasePitch, h.BaseVolume
	h.Release = placeSound(s, o.At, def)
	h:Apply()
	s.TimePosition = (def.RandomStart ~= false and s.TimeLength > 0) and math.random() * s.TimeLength or 0
	s:Play()
	-- fade in (Scale 0 -> 1)
	local fadeIn = o.FadeIn or def.FadeIn or .25
	local t0 = os.clock()
	task.spawn(function()
		while not h.Done and h.Scale < 1 do
			h.Scale = math.min(1, (os.clock() - t0) / math.max(.01, fadeIn))
			h:Apply()
			RunService.Heartbeat:Wait()
		end
	end)
	table.insert(loops, h)
	return h
end
-- stop every loop of a cue (or all loops) with a fade
function K.StopLoops(name, fade)
	for _, h in loops do if not name or h.Name == name then h:Stop(fade or .3) end end
end
function K.StopAll(fade)
	for _, h in playing do h:Stop(fade or 0) end
	K.StopLoops(nil, fade)
end
-- warm the cache for a list of cue names (or every cue) in the background
function K.Preload(names)
	if not K.IsClient then return end
	task.spawn(function()
		local list = {}
		for name, def in Cues do
			if not names or table.find(names, name) then
				for _, f in filesFor(name, def) do
					local s = Instance.new("Sound")
					s.SoundId = f.Id
					table.insert(list, s)
				end
			end
		end
		if #list > 0 then pcall(ContentProvider.PreloadAsync, ContentProvider, list) end
		for _, s in list do s:Destroy() end
	end)
end
-- cue helpers for the UI and shows
function K.Has(name)
	local def = Cues[name]
	return def ~= nil and #filesFor(name, def) > 0
end
-- a numbered ladder: K.Ladder("LuckImpact", tier, o) plays LuckImpact<tier> clamped to the cues that exist
function K.Ladder(prefix, n, o)
	n = math.floor(tonumber(n) or 1)
	while n > 1 and not Cues[prefix .. n] do n -= 1 end
	return K.Play(prefix .. n, o)
end

if K.IsClient then
	for name in K.Defaults do group(name) end
end
return K
