-- FarmLasso.SoundIds: asset ids of the sound pack (audio/pack/*.ogg). Upload each file as an Audio asset and paste
-- its id as "rbxassetid://<id>" on its line. An empty string means "not uploaded yet": SoundKit plays nothing for
-- that file and warns once, so the game runs with a half-uploaded pack. Generated by audio/build_sfx_pack.py --lua
-- (it keeps the ids already pasted in). Keys are the pack file stems; SoundCues refers to them by these keys.
return {
	-- AmbBirds (loop)
	amb_birds = "",
	-- AmbFountain (loop)
	amb_fountain = "",
	-- AmbWind (loop)
	amb_wind = "",
	-- AnimalBarnCat
	animal_barn_cat_1 = "",
	animal_barn_cat_2 = "",
	-- AnimalBarnOwl
	animal_barn_owl_1 = "",
	animal_barn_owl_2 = "",
	-- AnimalBillyGoat
	animal_billy_goat_1 = "",
	animal_billy_goat_2 = "",
	-- AnimalBison
	animal_bison_1 = "",
	animal_bison_2 = "",
	-- AnimalBunny
	animal_bunny_1 = "",
	animal_bunny_2 = "",
	-- AnimalChestnutHorse
	animal_chestnut_horse_1 = "",
	animal_chestnut_horse_2 = "",
	-- AnimalChick
	animal_chick_1 = "",
	animal_chick_2 = "",
	-- AnimalDairyCow
	animal_dairy_cow_1 = "",
	animal_dairy_cow_2 = "",
	-- AnimalDonkey
	animal_donkey_1 = "",
	animal_donkey_2 = "",
	-- AnimalGeneric
	animal_generic_1 = "",
	animal_generic_2 = "",
	animal_generic_3 = "",
	-- AnimalGoldenRooster
	animal_golden_rooster_1 = "",
	animal_golden_rooster_2 = "",
	-- AnimalGoose
	animal_goose_1 = "",
	animal_goose_2 = "",
	-- AnimalHen
	animal_hen_1 = "",
	animal_hen_2 = "",
	-- AnimalHighlandBull
	animal_highland_bull_1 = "",
	animal_highland_bull_2 = "",
	-- AnimalLlama
	animal_llama_1 = "",
	animal_llama_2 = "",
	-- AnimalOstrich
	animal_ostrich_1 = "",
	animal_ostrich_2 = "",
	-- AnimalPeacock
	animal_peacock_1 = "",
	animal_peacock_2 = "",
	-- AnimalPig
	animal_pig_1 = "",
	animal_pig_2 = "",
	-- AnimalPuddleDuck
	animal_puddle_duck_1 = "",
	animal_puddle_duck_2 = "",
	-- AnimalRedFox
	animal_red_fox_1 = "",
	animal_red_fox_2 = "",
	-- AnimalReindeer
	animal_reindeer_1 = "",
	animal_reindeer_2 = "",
	-- AnimalSheepdog
	animal_sheepdog_1 = "",
	animal_sheepdog_2 = "",
	-- AnimalTurkey
	animal_turkey_1 = "",
	animal_turkey_2 = "",
	-- AnimalUnicornPony
	animal_unicorn_pony_1 = "",
	animal_unicorn_pony_2 = "",
	-- AnimalWoollySheep
	animal_woolly_sheep_1 = "",
	animal_woolly_sheep_2 = "",
	-- ArcCrackle (loop)
	arc_crackle = "",
	-- BagFull
	bag_full = "",
	-- BullCharge
	bull_charge = "",
	-- Buy
	purchase_chime = "",
	-- CatchChime
	catch_chime = "",
	-- CatchPop
	catch_pop = "",
	-- CelBed (loop)
	cel_bed = "",
	-- CelChargeUp
	cel_charge_up = "",
	-- CelDetonate
	cel_detonate = "",
	-- CelImpact
	cel_impact = "",
	-- CelLand
	cel_land = "",
	-- CelRiser
	cel_riser = "",
	-- CelShimmer
	cel_shimmer = "",
	-- CelShockwave
	cel_shockwave = "",
	-- CelTitle
	cel_title = "",
	-- CelWhooshL
	cel_whoosh_l = "",
	-- CelWhooshS
	cel_whoosh_s = "",
	-- CharCrackle (loop)
	char_crackle = "",
	-- ClockTick (loop)
	clock_tick = "",
	-- CoinRain (loop)
	coin_rain = "",
	-- CoinSpiral
	coin_spiral = "",
	-- ConstellationPull
	constellation_pull = "",
	-- CosmicHum (loop)
	cosmic_hum = "",
	-- EmberSparkle
	ember_sparkle = "",
	-- Equip
	equip_click = "",
	-- Escape
	rope_slip = "",
	-- Fanfare1
	fanfare_1 = "",
	-- Fanfare2
	fanfare_2 = "",
	-- Fanfare3
	fanfare_3 = "",
	-- Fanfare4
	fanfare_4 = "",
	-- FeatherLand
	feather_land = "",
	-- FireWhoosh
	fire_whoosh = "",
	-- GemCrown
	gem_crown = "",
	-- GhostHooves (loop)
	ghost_hooves = "",
	-- GlassBreak
	glass_break = "",
	-- GlassShatter
	glass_shatter = "",
	-- HaloLand
	halo_land = "",
	-- HerdJoin
	herd_join = "",
	-- Hooked
	hooked = "",
	-- IceCrack
	ice_crack = "",
	-- LassoCharge (loop)
	lasso_charge_loop = "",
	-- LighthouseSweep
	lighthouse_sweep_1 = "",
	lighthouse_sweep_2 = "",
	lighthouse_sweep_3 = "",
	-- LotusBloom
	lotus_bloom = "",
	-- LuckImpact1
	luck_impact_1 = "",
	-- LuckImpact2
	luck_impact_2 = "",
	-- LuckImpact3
	luck_impact_3 = "",
	-- LuckImpact4
	luck_impact_4 = "",
	-- LuckTick
	luck_tick = "",
	-- MeterGood
	meter_good = "",
	-- MeterMega
	meter_mega = "",
	-- MeterPerfect
	meter_perfect = "",
	-- MusicCountry (loop)
	music_countryside = "",
	-- NoCoins
	error_buzz = "",
	-- PanelClose
	panel_close = "",
	-- PanelOpen
	panel_open = "",
	-- PetalShimmer (loop)
	petal_shimmer = "",
	-- PortalOpen
	portal_open = "",
	-- QuestAccept
	quest_accept = "",
	-- QuestComplete
	quest_complete = "",
	-- QuestTick
	quest_tick = "",
	-- RareReveal1
	rare_reveal_1 = "",
	-- RareReveal2
	rare_reveal_2 = "",
	-- RareReveal3
	rare_reveal_3 = "",
	-- RareReveal4
	rare_reveal_4 = "",
	-- RareReveal5
	rare_reveal_5 = "",
	-- RareReveal6
	rare_reveal_6 = "",
	-- RareReveal7
	rare_reveal_7 = "",
	-- ReverseWhoosh
	reverse_whoosh = "",
	-- Rewind
	rewind = "",
	-- RopeLand
	rope_land = "",
	-- RopeWhirl (loop)
	rope_whirl = "",
	-- SellDing
	register_ding = "",
	-- SellShower
	coin_shower = "",
	-- SpiritBellow
	spirit_bellow = "",
	-- StarChime
	star_chime = "",
	-- StarMapResolve
	star_map_resolve = "",
	-- StarTwinkle
	star_twinkle_1 = "",
	star_twinkle_2 = "",
	star_twinkle_3 = "",
	-- StepChime
	step_chime_1 = "",
	step_chime_2 = "",
	step_chime_3 = "",
	step_chime_4 = "",
	step_chime_5 = "",
	step_chime_6 = "",
	step_chime_7 = "",
	step_chime_8 = "",
	-- StepDirt
	step_dirt_1 = "",
	step_dirt_2 = "",
	step_dirt_3 = "",
	step_dirt_4 = "",
	-- StepGrass
	step_grass_1 = "",
	step_grass_2 = "",
	step_grass_3 = "",
	step_grass_4 = "",
	-- StepStone
	step_stone_1 = "",
	step_stone_2 = "",
	step_stone_3 = "",
	step_stone_4 = "",
	-- StepWood
	step_wood_1 = "",
	step_wood_2 = "",
	step_wood_3 = "",
	step_wood_4 = "",
	-- StingGood
	sting_good = "",
	-- StingMega
	sting_mega = "",
	-- StingPerfect
	sting_perfect = "",
	-- StormRoll (loop)
	storm_roll = "",
	-- SuckDrone (loop)
	suck_drone = "",
	-- SunDive
	sun_dive = "",
	-- Supernova
	supernova = "",
	-- TabSwitch
	tab_switch = "",
	-- Throw
	throw_whoosh_1 = "",
	throw_whoosh_2 = "",
	throw_whoosh_3 = "",
	-- ThrowBig
	throw_big = "",
	-- ThunderCrack
	thunder_crack = "",
	-- ThunderPunch
	thunder_punch = "",
	-- TornadoSlam
	tornado_slam = "",
	-- TreeGrow
	tree_grow = "",
	-- TugDanger
	tug_danger = "",
	-- TugLoop (loop)
	tug_loop = "",
	-- TugTick
	tug_tick_1 = "",
	tug_tick_2 = "",
	tug_tick_3 = "",
	-- UIClick
	ui_click_1 = "",
	ui_click_2 = "",
	-- UIHover
	ui_hover = "",
	-- WindFunnel (loop)
	wind_funnel = "",
	-- WingFlap
	wing_flap_1 = "",
	wing_flap_2 = "",
	wing_flap_3 = "",
}
