#!/usr/bin/env python3
"""
build_sfx_pack.py -- renders the Farm Lasso sound pack.

Re-run with:   python3 -I build_sfx_pack.py            (everything)
               python3 -I build_sfx_pack.py --only Catch    (names containing "Catch")
               python3 -I build_sfx_pack.py --list
               python3 -I build_sfx_pack.py --lua           (also rewrite src/.../SoundIds.lua, keeping filled ids)

Writes audio/pack/<file>.ogg for every registered recipe (variants as <file>_1.ogg, _2.ogg ...), audio/pack/manifest.json
and audio/contact_sheet.png (one spectrogram strip per file). Deterministic: a re-run makes the same files.
"""
import argparse
import json
import os
import re
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import numpy as np  # noqa: E402

import synth  # noqa: E402
from synth import REGISTRY, SR  # noqa: E402

PACK = os.path.join(HERE, "pack")
LUA_IDS = os.path.join(HERE, "..", "src", "ReplicatedStorage", "FarmLasso", "SoundIds.lua")


def load_recipes():
    for mod in ("recipes_game", "recipes_celebration"):
        try:
            __import__(mod)
        except ModuleNotFoundError as e:
            if e.name == mod:
                print(f"(no {mod}.py yet)")
            else:
                raise


def file_names(entry):
    if entry["variants"] == 1:
        return [entry["file"]]
    return [f"{entry['file']}_{i + 1}" for i in range(entry["variants"])]


def render(entry, only=None):
    out = []
    for v in range(entry["variants"]):
        fname = file_names(entry)[v]
        rng = synth.rng_for(entry["name"], v)
        t0 = time.time()
        x = entry["fn"](v, rng)
        x = synth.finish(x, loop=entry["loop"])
        if entry["stereo"] and x.ndim == 1:
            x = synth.stereo(x)
        if not entry["stereo"] and x.ndim == 2:
            x = x.mean(axis=0)
        path = os.path.join(PACK, fname + ".ogg")
        synth.write_ogg(path, x)
        secs = x.shape[-1] / SR
        print(f"  {fname:34s} {secs:6.2f} s  {'loop ' if entry['loop'] else '     '}{'st' if x.ndim == 2 else 'mo'}  ({time.time() - t0:.1f}s)")
        out.append((fname, secs, x))
    return out


def contact_sheet(rendered):
    from PIL import Image, ImageDraw
    W, H, PAD = 240, 48, 4
    cols = 4
    rows = (len(rendered) + cols - 1) // cols
    sheet = Image.new("RGB", (cols * (W + PAD) + PAD, rows * (H + 14 + PAD) + PAD), (24, 24, 28))
    d = ImageDraw.Draw(sheet)
    for i, (fname, secs, x) in enumerate(rendered):
        r, c = divmod(i, cols)
        x0, y0 = PAD + c * (W + PAD), PAD + r * (H + 14 + PAD)
        spec = synth.spectrogram(x, W, H)
        rgb = np.stack([spec * 1.0, spec * 0.75, spec * 0.35 + 30], axis=-1).clip(0, 255).astype(np.uint8)
        sheet.paste(Image.fromarray(rgb), (x0, y0 + 12))
        d.text((x0 + 2, y0), f"{fname}  {secs:.2f}s", fill=(230, 230, 230))
    sheet.save(os.path.join(HERE, "contact_sheet.png"))


def write_manifest(entries, rendered_by_name):
    man = {}
    for name, e in sorted(entries.items()):
        files = file_names(e)
        man[name] = {"files": files, "loop": e["loop"], "stereo": e["stereo"],
                     "seconds": [round(s, 3) for _, s, _ in rendered_by_name.get(name, [])] or None}
    with open(os.path.join(PACK, "manifest.json"), "w") as f:
        json.dump(man, f, indent=1, sort_keys=True)


def write_lua(entries):
    """SoundIds.lua: one line per pack file, keeping any rbxassetid already pasted in."""
    existing = {}
    if os.path.exists(LUA_IDS):
        for m in re.finditer(r'\["?([A-Za-z0-9_]+)"?\]?\s*=\s*"([^"]*)"', open(LUA_IDS).read()):
            if m.group(2):
                existing[m.group(1)] = m.group(2)
    lines = [
        "-- FarmLasso.SoundIds: asset ids of the sound pack (audio/pack/*.ogg). Upload each file as an Audio asset and paste",
        '-- its id as "rbxassetid://<id>" on its line. An empty string means "not uploaded yet": SoundKit plays nothing for',
        "-- that file and warns once, so the game runs with a half-uploaded pack. Generated by audio/build_sfx_pack.py --lua",
        "-- (it keeps the ids already pasted in). Keys are the pack file stems; SoundCues refers to them by these keys.",
        "return {",
    ]
    for name, e in sorted(entries.items()):
        lines.append(f"\t-- {name}{' (loop)' if e['loop'] else ''}")
        for fname in file_names(e):
            lines.append(f'\t{fname} = "{existing.get(fname, "")}",')
    lines.append("}")
    with open(LUA_IDS, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {os.path.relpath(LUA_IDS)} ({sum(len(file_names(e)) for e in entries.values())} files)")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", default=None, help="substring filter on the cue name")
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--lua", action="store_true", help="rewrite SoundIds.lua from the registry")
    ap.add_argument("--no-sheet", action="store_true")
    a = ap.parse_args()
    load_recipes()
    entries = {k: v for k, v in REGISTRY.items() if not a.only or a.only.lower() in k.lower()}
    if a.list:
        for k, e in sorted(entries.items()):
            print(f"{k:28s} {e['file']:30s} x{e['variants']} {'loop' if e['loop'] else ''}")
        return
    os.makedirs(PACK, exist_ok=True)
    rendered, by_name = [], {}
    t0 = time.time()
    for name in sorted(entries):
        e = entries[name]
        print(name)
        r = render(e)
        rendered += r
        by_name[name] = r
    if not a.only:
        write_manifest(entries, by_name)
    if a.lua:
        write_lua(REGISTRY)
    if rendered and not a.no_sheet and not a.only:
        contact_sheet(rendered)
    print(f"{len(rendered)} files in {time.time() - t0:.1f}s -> {os.path.relpath(PACK)}")


if __name__ == "__main__":
    main()
